title: Site
options:
  template: false
pages:
  template: section
files: true
fields:
  title:
    label: Site Title
    type:  text
  favicon:
    label: favicon
    type: selector
    mode: single
    types:
     - image
  headSnippets:
    label: Snippet Codes (Head)
    description: This content will be inserted into the <head> of the document. Be sure to include any wrapping `<script>` tags.
    type: textarea
    buttons: false
    font: monospace
    size: large 
  bodySnippets:
    label: Snippet Codes (Body)
    description: This content will be inserted into the <body> of the document.
    type: textarea
    buttons: false
    font: monospace
    size: large 
 
