title: Site
options:
  template: false
pages:
  template: section
files: true
fields:
  title:
    label: Site Title
    type:  text
  favicon:
    label: favicon
    type: selector
    mode: single
    types:
     - image